services:
  cardinal:
    build:
      context: ./cardinal
    ports:
      - "8081:80"
    volumes:
      - ./cardinal:/code
      - ./logs:/code/logs
    env_file:
      - ./cardinal/.env
    networks:
      - mynetwork
    user: root

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8082:80"
    networks:
      - mynetwork
    depends_on:
      - cardinal

networks:
  mynetwork:
    driver: bridge